import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const read = (path: string) => readFileSync(join(ROOT, path), 'utf8');

test('privacy discloses unlisted-link, inactive-alert and deletion behavior', () => {
  const privacy = read('site/src/pages/privacy.astro');
  assert.match(privacy, /one-way SHA-256 hash of the link's bearer token/);
  assert.match(privacy, /does not store the readable bearer token in D1/);
  assert.match(privacy, /browser history and in Cloudflare's ordinary request and security logs/);
  assert.match(privacy, /Anyone who receives the link can view the selected plan and server-generated quote/);
  assert.match(privacy, /internal harness names, usage assumptions and custom or contract rates/);
  assert.match(privacy, /does not include your Clerk account ID, email or other account profile data/);
  assert.match(privacy, /These settings are explicitly inactive: no monitoring job runs/);
  assert.match(privacy, /unlisted-link settings and token hashes, inactive alert settings, operation-replay records/);
  assert.match(privacy, /every affected unlisted link stops resolving/);
  assert.match(privacy, /authoritative for at most 24 hours/);
  assert.match(privacy, /pruned on that account's next operation/);
  assert.match(privacy, /seven closed first-party signal names in one server-selected signal version/);
  assert.match(privacy, /closed <code>pro_19_monthly_190_annual_v1<\/code> price experiment/);
  assert.match(privacy, /browser can submit only a random event UUID and one of four names/);
  assert.match(privacy, /untrusted, directional distinct-account signals—not as proof that an action occurred/);
  assert.match(privacy, /generated by the server only after the corresponding authenticated D1 operation succeeds/);
  assert.match(privacy, /server-selected signal version and price-experiment ID, a random event UUID used to make retries idempotent/);
  assert.match(privacy, /verified Clerk account ID, a server receipt timestamp and a 90-day expiry timestamp/);
  assert.match(privacy, /does not store the request body, page path, plan or harness names, model choices, token counts, prices, rates, thresholds, exported files or bearer URLs/);
  assert.match(privacy, /at most one row per account, event name, signal version and price experiment/);
  assert.match(privacy, /hard upper cap of 512 retained rows per account/);
  assert.match(privacy, /browser endpoint accepts exactly the UUID and allowed name and does not return submitted event fields/);
  assert.match(privacy, /server-selected signal versions and price-experiment IDs/);
  assert.match(privacy, /product-intent and per-account rate-limit records/);
  assert.match(privacy, /product-intent row expires after 90 days/);
  assert.match(privacy, /pruned on that account's next product-intent write or when the account is erased/);
});

test('terms explain bearer-link responsibility and never imply alert delivery', () => {
  const terms = read('site/src/pages/terms.astro');
  assert.match(terms, /An unlisted Build Composer link is a bearer link/);
  assert.match(terms, /“Unlisted” does not mean encrypted for a named recipient/);
  assert.match(terms, /handle it as sensitive information/);
  assert.match(terms, /Saving an alert setting does not start monitoring or delivery/);
  assert.match(terms, /will not check the setting on a schedule or send an email/);
});
